apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - port: 8089           # SPRING BOOT PORT
      targetPort: 8089     # INTERNAL CONTAINER PORT
      nodePort: 30080      # EXTERNAL PORT
